### ISSUE TITLE
Finish all mob levels for Ashenvale / Felwood

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#11]

**Comment by godbit** [comment]
@mewmew suggested Alpha-test with Imperios on friday. Would that work for you and do you think it is possible to achive?

**Comment by mewmew** [comment]
Inviting @7i to the conversation :)

**Comment by karlek** [comment]
I'm booked on friday and I also need to study inb4 flervarren so there probably won't be many more long sessions before I leave.

**Comment by godbit** [comment]
Ok i see!

**Comment by karlek** [comment]
Related #69
