### ISSUE TITLE
Write an automatic tower calculations updater

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#13]

**Comment by karlek** [comment]
Quite easy with `strings.HasPrefix` and https://developers.google.com/sheets/api/quickstart/go

Just need to solve filename, maybe with a filename field?

**Comment by godbit** [comment]
Cool, it would be really nice to have it for easy balance tweaking (globally). 

If we get this working it might be worth to do the same to generate mobs. It will still be hard to balance according to some formula but it can give a good perspective and it will be easy to make several changes at once 🏭

**Comment by karlek** [comment]
Yeah, so we would do it for the easy of updating rather than the balancing part. I agree. Do you want to do this together and learn a little go or should I go ahead and do it? @draftlord

**Comment by godbit** [comment]
Humm, it would be pretty nice to learn actually because reading info from a spreadsheet and using that data in a script seems useful in several situations.

**Comment by karlek** [comment]
We can do it in Python as well which might be a smaller stepping stone.

**Comment by karlek** [comment]
Implemented with https://github.com/lapsang-boys/exicon
