### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#22]

**Comment by karlek** [comment]
Apparently the maximum resolution for loading screens are 1024x768 which is then upscaled to the monitors resolution: so we have to scale down a widescreen image to 1024x768 which will then be stretched to widescreen in Wc3 haha

**Comment by godbit** [comment]
Haha ok, if we dont want the stretched image to look weird we could select an image with the correct ratio and then scale that down to 1024x768 which will make it have the correct proportions when stretched.

**Comment by karlek** [comment]
Related #76

**Comment by karlek** [comment]
Closing this for now
