### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#31]

**Comment by karlek** [comment]
Depends on #21

**Comment by godbit** [comment]
Sweet as desc bro :heart_eyes:

**Comment by godbit** [comment]
Blev typ taggad på "äventyret" när man läste!

**Comment by karlek** [comment]
Haha har varit så roligt att skriva den! Även om formattingen på github är sämst, tänker mig att du får sitta i InDesign och göra en bild av det hela 😏

**Comment by godbit** [comment]
Haha x) Kan jobba på lite bilder i Gimp iaf!
