### ISSUE TITLE
Periodic with phases

### ISSUE THREAD

**Issue by godbit** [Lapsang-boys/Rex-Temporis#35]
Create a mob type that is periodic, it switches states on periodic.

Game-play enhancing mechanic - forces the player to switch targets and avoid units in a certain state. 

For instance:
- In one states it gains increased movement speed if hit
- In other state reduced movement when hit

- One weaker state where damage is amplified etc.

**Comment by karlek** [comment]
Depends on #9

**Comment by karlek** [comment]
`maxIterations = 0` and `iteration modulo 2 == 0`

Shouldn't be difficult to implement.

**Comment by godbit** [comment]
Fixed in commit a061cd13a3bdb3f559de2ef5fdc9b96490ee76bb
