### ISSUE TITLE
Fix description for finalized levels

### ISSUE THREAD

**Issue by godbit** [Lapsang-boys/Rex-Temporis#36]
The levels currently have the wrong description and MobType. Needs to be fixed for all levels before Zone 1.

@karlek continuous development or fix all when finalizing Zone 1? 🔨

**Comment by karlek** [comment]
Night of lore? 🌃

**Comment by godbit** [comment]
👍

**Comment by karlek** [comment]
Have we decided to scrap MobType since basically every level is special now?

**Comment by godbit** [comment]
Yeah, maybe we should add a function to the tooltip package to generate descriptions instead? It would be nice to have it in some sort of list format so that you can describe several mobs in a clean way.

Also implement -info or something to display next levels info, since it is actually pretty much impossible to adapt to a level once you have summoned it.

**Comment by karlek** [comment]
So maybe long vs short description format. Where short is used for info and long is used when the level spawns.

Should we have them bundled into levels? It would be quite nice for info:

```wurst
Level l = ...
printForPlayer(..., l.descriptionLong())

// Or for info

for i = pd.level to pd.level+5
    if i >= levels.size()
        break
    printForPlayer(..., levels.get(I). descriptionShort())
```
