### ISSUE TITLE
Find an alternative way to stop MobMissile

### ISSUE THREAD

**Issue by godbit** [Lapsang-boys/Rex-Temporis#41]
MobMissile currently uses pre-calculation to determine how long it will be in the air  -> this time-stamp determines when to stop iterating and releasing the mob.  This method does not work if the terrain is flat since the airtime calculated will not be correct.

Probable other solution:
 - Check if fly-height > 0
 
Note: This check did not work when i was developing the system but that might be because the system it self was not fully working.

**Comment by karlek** [comment]
How did you do it?

**Comment by godbit** [comment]
`if mm.u.getFlyHeight() <= 0.1`

Apparently the flyheight is 0.010 and not 0 which is why the old check failed. I

 have yet to try this with different elevations though.. I know that the landing-spot compution will probably be wrong when there are height differences. But this kind of depends on how fly-works since with normal units with movement type flying the fly height remains constant relative to the ground when moving over different heights.
