### ISSUE TITLE
Add no-go regions for MobMissile

### ISSUE THREAD

**Issue by godbit** [Lapsang-boys/Rex-Temporis#43]
The MobMissile can in **RARE** cases land where it is not supposed to, for instance in the water zone-1 👼 

To avoid this we could add regions within the zone where the unit is not supposed to land and make sure that the computed landing spot is not in one of those.

**Comment by karlek** [comment]
"__RARE__".

**Comment by godbit** [comment]
There are no logs of it ever happening but you can never be to safe 😎

**Comment by karlek** [comment]
I don't think adding regions for every risky part in an area, for every player, for every zone is good coding style. Even though the terrain will probably be quite permanent, it makes us much less able to update the terrain if we actually want to.

Can we for instance check if the target position has a lower z-level or add pathing blockers etc?

**Comment by godbit** [comment]
Yeah i agree its a pretty nasty solution. We can probably figure something out together.
