### ISSUE TITLE
Script that generates mob for different difficulties

### ISSUE THREAD

**Issue by godbit** [Lapsang-boys/Rex-Temporis#45]
We need to write a script that generates 3 sets of mobs, one for each difficulty. The property changed will be maxhp.

Either we do it like this (roughly):
- Easy 60% of hp
- Normal 80%
- Hard 100%

Or
- Easy 80% of hp
- Normal 100%
- Hard 120%

Additionally we might want hardcore depending on how we want to go about balancing. For instance 10% more health than hard.

**Comment by karlek** [comment]
I vote for formula number 1: 60%, 80% and 100% since we will balance for 100%

**Comment by karlek** [comment]
Closed in: cdfb804f82e1b2b8f33bea6163250bc3b86e952b
