### ISSUE TITLE
Pitlord

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#54]
Pitlord has two abilities:

__OnEnter__
_Rain of Fire_: find location with highest collected tower gold costs (`getPointValue`), cast rain of fire and stun for X seconds.

__Periodic (OnLife)__
_Infernal_: when Pitlord's life reaches a certain value it casts an infernal on the last node it has reached. The infernal has a time-to-live fading towards darker colors. If not killed when the timer expires, the infernal will explode with `UExplosion` and cast death coil with possession model file on Pitlord. Pitlord will then regain health and start the Walk Fast animation with increase movement speed.

Fix so that the HP trigger only works once, hence the heal from the infernal won't trigger the same infernal spawning twice.

Should happen about 9~ times (11.11% of life repeating of course).

__Exposition__

_Text tags_: the pitlord will say some lines when doing some of his spells to inform the player of his actions.

_Info_: for unskilled players, write an info message and play the info message sound with a hint.
If the player dies then we print the remake boss command.

**Comment by godbit** [comment]
Initial work: 93a75154032bc411edde66cf7ae4cf0ec72bcafc

Only needs polish.

**Comment by godbit** [comment]
I consider this as closed. Everything works, only minor tweaks are needed (if anything is needed at all).
