### ISSUE TITLE
Keep it Lapsang

### ISSUE THREAD

**Issue by mewmew** [Lapsang-boys/Rex-Temporis#64]
Drack lapsang idag och fick då tanken för denna issue.

ping @karlek and @godbit

Vore kul att få till en gruppchat vi alla har tillgång till, och enligt Emils analys verkar GitHub täcka våra behov :cactus:

Så! Vad händer i allas liv? Några roliga äventyr på sistone?

Jag kom precis ned till New Orleans med de andra i Studs. Har varit sjukt kul att lufsa runt, och idag var vi förbi träsken i Luisiana och kajakade längs alligatorer. Vet att Mamsen sätter sig på planet till Sendai imorn.

Vi hörs och ses!

*glada kramar*
Robin

Graffarna hemma håller på att bli bättre, sakta men säkert.

![2018-06-12 - 04 57 53_mini](https://user-images.githubusercontent.com/1414531/41625190-79f82c42-7407-11e8-8585-baee0e303e7b.jpg)

Graffarna i Staterna är rätt skillade.

![2018-06-13 - 18 19 52_mini](https://user-images.githubusercontent.com/1414531/41625221-97f979bc-7407-11e8-8993-f21552ceafca.jpg)

Från första hotellet i New York :)

![2018-06-16 - 08 03 15_mini](https://user-images.githubusercontent.com/1414531/41625233-a0ea6f7c-7407-11e8-9729-d30b1ee300c0.jpg)

Från Kajakandet idag, sjukt coola klängväxter på träden; kallas Spanish moss (trots att den varken är spansk eller mossa).

![2018-06-19 - 19 58 40_mini](https://user-images.githubusercontent.com/1414531/41625248-ac59670a-7407-11e8-9ad1-538a4c5f9a51.jpg)

Kajakande.

![2018-06-19 - 20 17 38_mini](https://user-images.githubusercontent.com/1414531/41625282-cfaa6d6c-7407-11e8-9608-10bdc40b8d5c.jpg)

**Comment by karlek** [comment]
Hej bror! 

Ja, vi får ta och skicka kidsen på klassresor till staterna så de får lite inspo!

Kajaka längs alligatorer låter riktigt ballt! Ser dock ut som att det borde finnas rikligt med mygg. New Orleans skulle jag vilja besöka någon gång, live musik och den där fesitvalen de har som jag enbart minns från Malcolm in the Middle när Francis ligger sjuk på hotellrummet.

Mamsen landar här imorgon torsdag kl 12, sen lär hon väl vara jetlaggad som en klubbad säl haha.

I helgen besökte jag ett Sakébryggeri och kollat på VM-matcherna. Är ju inte mycket för fotboll på TV, men umgänget och galna japaner som firar VM var härligt att se. Lärt mig spela brädspelet Go, vilket är en blandning av enkla reglar och oerhört komplexa matcher. Åkte och kollade på en vulkankratersjö, riktigt ball faktiskt! Är nog inte lika actionpackad resa som STUDS, farligaste djuret vi har här är varmakällbadande apor ;)

![out](https://user-images.githubusercontent.com/1278705/41640411-ba63f47e-749c-11e8-975c-b899589cea2a.jpg)

Var med på en miko-dansuppvisning.

![p1150501](https://user-images.githubusercontent.com/1278705/41640245-0241855a-749c-11e8-9c1a-31fa895e7548.jpg)

En tysk i samurai-utstyrsel.

![p1150132](https://user-images.githubusercontent.com/1278705/41640270-168510f4-749c-11e8-9c00-b1dcb8db0118.jpg)

Cyberpunkjapan i Nagoya

![out](https://user-images.githubusercontent.com/1278705/41640402-ad7379a6-749c-11e8-8ab8-a6de22298f82.jpg)

Parkeringsplatsen vi var fast på i några timmar när vi liftade ner till Tokyo.

**Comment by godbit** [comment]
Kul att höra från er boys och bara initiativ @mewmew! 🗾 🇺🇸  Verkar som att ni hittar på mycket nice stuff. Här hemma händer det inte jättemycket, men har precis börjat jobba (ska jobba 2.5 veckor och sen  lite ledigt innan det bär av till tank). 

Lever just nu i en totalt maxad 1a i väntan på att få flytta in i kungshamra 15a:
![20180620_184430](https://user-images.githubusercontent.com/13339679/41672543-732b42c4-74ba-11e8-9326-1e537425d90a.jpg)

Verktyg och mtg-kort förvaras där det finns plats:
![20180620_184453](https://user-images.githubusercontent.com/13339679/41672553-7ba88646-74ba-11e8-9836-b56bd1de1a06.jpg)

Förra veckan cyklade jag till Skåne med Noah, riktigt nice men också slitsam semester. Kul att se Sverige!

Jävligt nöjd med den nya cykeln som här poserar på sveriges längsta strand 😍:
![lrm_export_20180614_165925](https://user-images.githubusercontent.com/13339679/41672663-c7a716f2-74ba-11e8-93d8-4985d8d2b5f8.jpg)

Poserar på klipporna 1 mil utanför Norrköping:
![lrm_export_20180611_141214](https://user-images.githubusercontent.com/13339679/41672689-d7f83c7a-74ba-11e8-9fb2-71d6bb30349f.jpg)

Fika i den småländska idyllen:
![lrm_export_20180613_181707](https://user-images.githubusercontent.com/13339679/41672702-e1eb826e-74ba-11e8-9f45-2a47ab62691b.jpg)

Pose efter den värsta climben jag gjort i mitt liv (över Hallandsåsen från Båstad):
![lrm_export_20180614_170820](https://user-images.githubusercontent.com/13339679/41672739-fbd27a98-74ba-11e8-9104-aa9d7efd741b.jpg)
 
Sist men inte minst, Peking Piglets officiella lagtröjor har äntligen levererats 😀:
![20180620_185436](https://user-images.githubusercontent.com/13339679/41672936-8c794ce8-74bb-11e8-97a8-5b2a8d8c45d4.jpg)

**Comment by mewmew** [comment]
# Bror 1

> Kajaka längs alligatorer låter riktigt ballt! Ser dock ut som att det borde finnas rikligt med mygg.

Slapp mygg och fick en dag med moln så sjukt bra time'at.

> New Orleans skulle jag vilja besöka någon gång, live musik och den där fesitvalen de har som jag enbart minns från Malcolm in the Middle när Francis ligger sjuk på hotellrummet.

Har varit kul att hänga lite på Jazz-barer. Bourbon street är kaos, tar en sig lite längre bort så går det att njuta. Fan taggad på att köra en Malcom in the Middle filmkväll i höst!

> Mamsen landar här imorgon torsdag kl 12, sen lär hon väl vara jetlaggad som en klubbad säl haha.

Sannerligen. Jag var lite vimmelkantig efter 12 timmar på flyg och tror hon sitter typ 16? Riktigt kul att mammut kom iväg! Hon är modig.

> Åkte och kollade på en vulkankratersjö, riktigt ball faktiskt!

Låter iofs fett coolt!

> Är nog inte lika actionpackad resa som STUDS, farligaste djuret vi har här är varmakällbadande apor ;)

Haha :)

> Parkeringsplatsen vi var fast på i några timmar när vi liftade ner till Tokyo.

Riktigt glad att du lufsar runt bror och får upptäcka mycket. Såväl hur du reagerar i olika situationer (skulle vilja veta mer om välden sett från han du liftade meds perspektiv) som ny kultur och härliga människor.

# Bror 2

> Lever just nu i en totalt maxad 1a i väntan på att få flytta in i kungshamra 15a:

Inflytt om 10 dagar?

> Förra veckan cyklade jag till Skåne med Noah, riktigt nice men också slitsam semester. Kul att se Sverige!

Fan vad coolt, fin tur att köra. Hur lång tid tog det att cykla och körde ni tält?

> Sist men inte minst, Peking Piglets officiella lagtröjor har äntligen levererats grinning:

Haha! Du ser riktigt boss ut i tröjan!

---

Idag var vi förbi ett av plantagen i Louisiana. På fre bär det vidare mot San Fran.

*kärlek och värme från den Amrikanska södern*

P.S. Jag har inge permissions att lägga till labels, ändra assignees etc. Just så ni know. ^^

**Comment by godbit** [comment]
> Inflytt om 10 dagar?

Jajamen, inflytt den 2/7 så kommer hinna preppa lite innan Japan men jag har kvar den gamla lägenheten till 15/8 så har gott om tid att flytta :)

> Fan vad coolt, fin tur att köra. Hur lång tid tog det att cykla och körde ni tält?

Aaa riktigt fint. Det tog oss fyra dagar att ta oss ner, då hade vi effektiv körtid på ca 5 - 6 timmar per dag, med rast osv så körde vi oftast ish 9 - 17. Nej vi hade inga cykelväskor så vi körde lättast möjliga packing och bodde på hotel/vandrarhem. 

Haha fast som permanent assigne @mewmew :rofl: 
<hr>

_Med kärlek och typiskt midsommarväder från Sverige_

**Comment by mewmew** [comment]
> Jajamen, inflytt den 2/7 så kommer hinna preppa lite innan Japan men jag har kvar den gamla lägenheten till 15/8 så har gott om tid att flytta :)

Soft.

> Haha fast som permanent assigne @mewmew :rofl:

Oh nooohes!

<3

**Comment by godbit** [comment]
Stänger, sommaren är över och Lapsang boys är tillbaka 🙏
