### ISSUE TITLE
Cleaving attack doesn't exist in AbilityIds (ACce)

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#75]
Remember to change Ancestral Sprit when this is fixed

**Comment by godbit** [comment]
An alternative to cleave could be to use pulverize (which is used by native taurens). It looks pretty cool when it procs and the animation is on point since it was designed for turens.

**Comment by karlek** [comment]
That's a better solution for the spell I had in mind, ty ty

**Comment by godbit** [comment]
No probs :bowing_man: 

Close this one?

**Comment by karlek** [comment]
Still need to push this upstream

**Comment by karlek** [comment]
https://github.com/wurstscript/WurstStdlib2/pull/114

**Comment by karlek** [comment]
Merged in upstream.
