### ISSUE TITLE
Fiverr - Minimap, Loading screen and Lapsang logo

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#76]
# Lapsang Studios logo

_Demands_:

Black and white

# Minimap icon

_Fiverr:_ https://www.fiverr.com/gulacandy
_Demands_: Square crop. 

## Ideas

**Books**

_Design:_

The book would depict the literal book: Crimson Chronicles

- Book with blood letters or red runes crackling with magic.
- Pages turning when a spirit leaves the pages.
- Open book with quill, feather and lantern

_References:_

https://wallpaperstudio10.com/static/wpdb/wallpapers/1920x1080/180055.jpg
For the magic book depiction.

**Flags**

_Design:_

The point being that the red flag could symbolize the bloody crusades depicted
in the Crimson Chronicles.

- Horseman holding a long wavy red flag on a battlefield.
- Flag standing on a desolate battlefield.

_References:_

https://www.artstation.com/artwork/Y4Pmb
For the art style and flag motif.

# Loading screen

_Fiverr:_ https://www.fiverr.com/gulacandy
_Demands_: Widescreen crop.

**Comment by karlek** [comment]
@godbit do you think we need a mood-board for the lapsang studios logo? I think our old logo + some descriptions are sufficient. Should we order these tonight? :camel: :palm_tree:

**Comment by godbit** [comment]
Yeah lets make the order tonight! :1st_place_medal: I think a small moodboard could be good but not at all as much labor as the other ones. Cant wait to see the result!

**Comment by karlek** [comment]
Logo has been ordered

---

Loading screen and minimap was too expensive to order.

**Comment by godbit** [comment]
Abondon ship on this. Creating a new issue for creating the logo ourselves.

**Comment by karlek** [comment]
End of an era :ship:

**Comment by godbit** [comment]
:bomb:
